services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: furnicraft_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - furnicraft_network

  redis:
    image: redis:8.4.0-alpine
    container_name: furnicraft-redis
    ports:
      - "6379:6379"
    networks:
      - furnicraft_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio:latest
    container_name: furnicraft-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    networks:
      - furnicraft_network
    restart: always

networks:
  furnicraft_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: