spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

application:
  services:
    auth:
      url: http://auth-service:8081
  security:
    internal:
      service-key: ${INTERNAL_SERVICE_KEY}