spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

application:
  services:
    auth:
      url: ${AUTH_SERVICE_URL}
  security:
    internal:
      service-key: ${INTERNAL_SERVICE_KEY}